---
title: "Considerations for R Package"
output: html_document
---

#Notes

* `mic_stat` isn't a model object, but should I still use `formula` and `model.frame` to ensure the appropriate columns are selected?  
* Need to make `pkm` able to produce prior estimates in absence of observed data...is it ok to initilize `formula` and `data` to `NULL`?  
* Write `print` method for `pkm`  
Actually, I haven't implemented this next bullet point yet. I would like to revisit it, since I think it feel more intuitive to force people to supply values on the mcg/mL (measurement) scale and manually convert within the function, rather than making them do the conversion on their own. It also seems more intuitive to enter "6 g/h" than to have to do "6,000 mg/h"  

* A note on units: functions have been recoded to have all inputs on the scale of interest: mcg/mL (**VERIFY** - we used to be providing information on the scale of mcg/mL then multiplying the pk solution by 1000 for unit compatibility. Now, we are forcing people to enter ...(rate?)... as mcg/mL)   
* Also in `predict.pkm` (check other functions)  

#Hmm...  

* Formulas are in place to grab the appropriate data for the observed concentration-time data, but not for the ivt matrix. Maybe make the `ivt_toList` function formula-oriented? Not sure it's feasible to have two formula inputs for functions set up to deal with concentraion ~ time  
* If it's not too over the top, could create a class for the ivt data frame and require those inputs to be of class `ivt`  


##Reminders  

* Change `mic_stat` to have `times` be a min/max (interval) argument, rather than a vector of times. Don't forget to appropriately change the output to match this  
* Add ui/server functions to produce shiny app  
* Change `cod` argument name to something more intuitive  
* Rename `pk_basic_solution` and `pk_solution` to more clearly delineate the difference  
* Come back to `log_prior`: Current have default values both coded into the function and as an example. Probably don't need both.  


##Questions  

* Rearrange prior/model function to depend on supplied mean/sd of distribution (not positive what distribution I meant here...)  
* How to structure the hyperparameters? Would draws from the hyperpriors be made within the log_prior function? (for a later version)  



